name: cd

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

env:
  RELEASE_PREFIX: "chore(main): release"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build binaries
        run: "GOOS=linux GOARCH=amd64 go build -o falcon-linux"

      - name: Create release artifacts
        run: "tar -czvf falcon-linux.tar.gz falcon-linux"

      - name: Create Release
        id: create_release
        uses: googleapis/release-please-action@v4
        with:
          release-type: go
          tag: "auto"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url}}
          repository: sshaparenko/falcon
          files: falcon-linux.tar.gz
