name: cd

on:
  push:
    branches: [main]
    paths:
      - "../bin/**"
      - ".github/workflows/cd.yml"

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  RELEASE_PREFIX: "chore(main): release"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: ls directory
        run: "ls -a"

      - name: Build binary file
        run: "GOOS=linux GOARCH=amd64 go build -o falcon.go"

      - name: Release with release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
