name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build binaries
        run: "GOOS=linux GOARCH=amd64 go build -o falcon-linux"

      - name: Create release artifacts
        run: "tar -czvf falcon-linux.tar.gz falcon-linux"

      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: go
          tag-name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v3
        with:
          upload_url: ${{ steps.release.outputs.upload_url }} # Upload to the release created by Release Please
          asset_path: ./falcon-linix.tar.gz # Path to your binary or asset
          asset_name: falcon-linix.tar.gz # Custom name for the asset
          asset_content_type: application/gzip
